### ISSUE TITLE
Create a Master node layer to monitor multiple miners from one machine

### ISSUE THREAD

**Issue by SmokinCache** [JerichoJones/JJ-s-XMR-STAK-HashRate-Monitor-and-Restart-Tool#11]
Use existing monitor on each miner and add package to monitor multiple monitors with slack/sms notifications if a miner stops responding. Had a process kill action cause windows to freeze and run GPUs 100%. Machine would no longer even respond to ping requests. Even better if master monitor could also support some power cycling device such as the TP-link HS100 or 110 if miner stops responding.

**Comment by JerichoJones** [comment]
This is probably beyond my meager abilities.

**Comment by SmokinCache** [comment]
Thought about this and I think you are underestimating your abilities! But if the monitor can get a SMS/Slack message out prior to the Kill this is probably a mute point.

**Comment by JerichoJones** [comment]
This goes back to the per thread request. Since, in the case you outline, I wouldn't care about which thread died. I could send a message that a thread died and maybe ID the number but I wouldn't know what device (AMD/NVIDIA/CPU) that it was.
I think that is doable.

**Comment by SmokinCache** [comment]
Device ID by the monitor is not important. I mapped which GPUs are running which thread. This is easy to do watching the hash rate and manipulating performance in ODT.

SLOT			              FANCTRL	TEMP	FREQ/hash    Thread
1 Vega64 in PCIEX16_1  	OD1	         GPU3	GPU5            10/11
2 Vega56 in PCIEX16_3  	OD2	 GPU0	GPU3            6/7
3 Vega64 in PCIEX1_1  	        OD3	 GPU2	GPU2            4/5
4 Vega56 in PCIEX1_3   	OD4	 GPU5	GPU1             2/3
5 Vega56 in PCIEX1_2   	OD5	 GPU4	GPU4            8/9
6 Vega56 in PCIEX1_4  	OD6	        GPU1	GPU0             0/1

**Comment by SmokinCache** [comment]
Continued inIssue #10
