### ISSUE TITLE
Slack notifications

### ISSUE THREAD

**Issue by briangig** [JerichoJones/JJ-s-XMR-STAK-HashRate-Monitor-and-Restart-Tool#6]
I wanted to be notified in real time if my hash rates dropped, so I added some Slack functionality to this script.

Here is one way to send to Slack with PS, and the one I used: https://www.reddit.com/r/sysadmin/comments/4fyrwg/slack_notifications_from_powershell/?st=jaqzuq5s&sh=038323d3

First step is to create your webhook in Slack.  For more info on creating webhooks in Slack, check out https://get.slack.help/hc/en-us/articles/115005265063-Incoming-WebHooks-for-Slack.

Now for adding in the code.  When done, we will get notifications to the channel named #mining when:

- Hash rate drops and the script begins the device(s) reset
- The devices in the system are reset successfully
- The initial hash rate and calculated drop rate

First add in the Send-SlackMessage function.  I added mine at line 180 (in version 2.9), right above the reset-VegaDriver function.  Be sure to put in the correct URL for your webhook.

```
function Send-SlackMessage {
    # Add the "Incoming WebHooks" integration to get started: https://slack.com/apps/A0F7XDUAZ-incoming-webhooks
    param (
        [Parameter(Mandatory=$true, Position=0)]$Text,
        $Url="https://hooks.slack.com/services/T7052EN/B801E/xxxxxxxxxxx", #Put your URL here so you don't have to specify it every time.
        # Parameters below are optional and will fall back to the default setting for the webhook.
        $Username, # Username to send from.
        $Channel, # Channel to post message. Can be in the format "@username" or "#channel"
        $Emoji, # Example: ":bangbang:".
        $IconUrl # Url for an icon to use.
    )
        $body = @{ text=$Text; channel=$Channel; username=$Username; icon_emoji=$Emoji; icon_url=$IconUrl } | ConvertTo-Json
        Invoke-WebRequest -Method Post -Uri $Url -Body $body
}
```

Now we can add the code in the right spots to call the above function.  At Line 217, in the `reset-VegaDriver` function, add:

`Send-SlackMessage "Device reset completed on $env:computername." -Emoji ":fire:" -Channel "#mining"`

Now locate the line `log-Write ("$timeStamp	Starting Hashrate: $global:maxhash H/s	Drop Target Hashrate: $global:rTarget H/s")`.  Below this, enter:

`Send-SlackMessage "Starting Hashrate on $env:computername - $global:maxhash H/s.  Drop Target Hashrate - $global:rTarget H/s" -Emoji ":fire:" -Channel "#mining"`

Then, at around line 467, inside the brackets the `If ($flag -eq "True")`, add:

`Send-SlackMessage "Device(s) resetting on $env:computername. Hash rate dropped from $global:maxhash H/`

Here is a screenshot of what a typical reset kicked off due to a hash rate drop will look like: https://i.imgur.com/9W4WNJU.png

If you get red text in the monitoring tool during a device reset and are on Windows 10, make sure you have opened Internet Explorer at least once to initialize it in Windows.

**Comment by JerichoJones** [comment]
Thanks! I'll look into this at some point relatively soon.

**Comment by micahvandeusen** [comment]
@briangig This is a really cool idea. I used the same setup you used and it worked for me. I did change it to redirect the output of Invoke-WebRequest to null. It was causing problems with the display window.

**Comment by JerichoJones** [comment]
FYI... there is a lot more error checking in v3.1... more Slack opportunities. :-)
I'm working on the slack code... it may be included in the next release. SMS messaging will definitely be in it.

**Comment by JerichoJones** [comment]
Slack code is integrated.  Testing good so far...
![image](https://user-images.githubusercontent.com/13205729/33586852-6cef8cb6-d939-11e7-8ec2-20994702d889.png)

**Comment by JerichoJones** [comment]
Version 3.2 has been posted to dev. Slack integration has been included. Thanks for the pointers.

**Comment by JerichoJones** [comment]
Feature is functional.
