### ISSUE TITLE
Disable CPU and Nvidia mining from config file?

### ISSUE THREAD

**Issue by sifotes** [JerichoJones/JJ-s-XMR-STAK-HashRate-Monitor-and-Restart-Tool#9]
I've looked through a few different sections but I can't find anywhere that actually disables nvidia mining when adding --noNVIDIA. Any suggestions?

**Comment by JerichoJones** [comment]
Did you unremark the $global:STAKcmdline variable? It is set to disable NVIDIA by default.
#$global:STAKcmdline = "--noNVIDIA"	# STAK arguments. Not required, REMARK out if not needed

**Comment by sifotes** [comment]
That's what I was looking for, thanks!
